// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_ElKsqwbYmWMwsadCB6-Ov5JdmgP-7c',
    appId: '1:668634441558:android:6f461dc7239f507959d8f7',
    messagingSenderId: '668634441558',
    projectId: 'aiinvoicemaker-3a0af',
    storageBucket: 'aiinvoicemaker-3a0af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8CkSeXnQmVE0ATeh5_l516VikbDQaZ94',
    appId: '1:668634441558:ios:f39841e51e14ce6b59d8f7',
    messagingSenderId: '668634441558',
    projectId: 'aiinvoicemaker-3a0af',
    storageBucket: 'aiinvoicemaker-3a0af.firebasestorage.app',
    androidClientId: '668634441558-52c7rbu6ul7ohpgdptjnvslafj6gefcs.apps.googleusercontent.com',
    iosClientId: '668634441558-6h68dgai9ggkatekj6m6cihe3lqhi6ed.apps.googleusercontent.com',
    iosBundleId: 'com.invoice.maker.estimate.billing.ocr.appomatrix',
  );
}
